services:
  yourhabit.api:
    container_name: YourHabit.Api
    image: ${DOCKER_REGISTRY-}yourhabitapi
    build:
      context: .
      dockerfile: YourHabit.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://yourhabit.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://yourhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc

  # yourhabit.seq:
  #   image: datalust/seq:2024.3 # or latest
  #   environment:
  #     ACCEPT_EULA: "Y"
  #   volumes:
  #     - ./.containers/seq_data:/data
  #   ports:
  #     - 8080:80
  #     - 5341:5341

  yourhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
