// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YourHabit.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Rename_Description_Column : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "descriptions",
                schema: "your_habit",
                table: "habits",
                newName: "description");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "description",
                schema: "your_habit",
                table: "habits",
                newName: "descriptions");
        }
    }
}
